name: CI

on: [push, pull_request]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use Node.js version 10
      uses: actions/setup-node@v1
      with:
        node-version: '10'

    - name: Npm install
      run: npm install
    - name: Run test
      run: npm test
